### ISSUE TITLE
Hello what about 1.12.2 port? I was greatly inspired by this plugin

### ISSUE THREAD

**Issue by jdkezo** [MylesAndMore/Tumble#9]
I am very interested in this plugin, but the version of my server is 1.12.2 and many people play with this version, it would be great if you ported the plugin to this version! thank you very much for understanding

**Comment by MylesAndMore** [comment]
Glad that you're interested! The approach I recommend is running your server natively on 1.19 or 1.20 and then using ViaVersion and it's derivatives to allow 1.12 etc. players to connect.
I understand if that's not possible due to other plugins that only work on that version or other issues so I will look into porting to that version natively. Some versions are harder than others to port so I can't guarantee anything but I will try my best!

**Comment by MylesAndMore** [comment]
Hey @jdkezo, I've made a bit of an unofficial 1.12.2 port for you. I'm unable to test as I don't have a 1.12.2 server but you are welcome to test it out and let me know how it goes! I'm happy to fix any issues you may encounter.

I recommend testing this on a test server and NOT a production server as there could be bugs that the Java compiler has overlooked.

Happy playing!

[Download here](https://github.com/MylesAndMore/Tumble/files/12187518/Tumble-1.0.4-1.12.2.zip)
